server:
    interface: 127.0.0.1
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 127.0.0.0/8 allow
    username: ""
    chroot: ""
    directory: "/etc/unbound"
    pidfile: "/run/unbound.pid"
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
